/**
 * Export Reynolds seed data as SQLite INSERT statements
 * Run after seed:reynolds to generate portable SQL
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

function escape(val: unknown): string {
  if (val === null || val === undefined) return "NULL";
  if (typeof val === "number") return String(val);
  if (val instanceof Date) return `'${val.toISOString().slice(0, 19).replace("T", " ")}'`;
  return `'${String(val).replace(/'/g, "''")}'`;
}

async function main() {
  const periodStart = new Date(2026, 3, 1);
  const periodEnd = new Date(2026, 5, 30);
  const retailerNames = ["Walmart", "Sam's Club", "Kroger", "Target", "Walgreens"];

  const retailers = await prisma.retailer.findMany({
    where: { name: { in: retailerNames } },
  });
  const skus = await prisma.sKU.findMany({
    where: {
      skuCode: {
        in: ["RW75", "RW200", "HT30", "HSQt", "RP", "HSG"],
      },
    },
  });
  const events = await prisma.promoEvent.findMany({
    where: {
      retailerId: { in: retailers.map((r) => r.id) },
      periodStart: { lte: periodEnd },
      periodEnd: { gte: periodStart },
    },
    include: { sku: true, retailer: true },
    take: 100,
  });

  const lines: string[] = [
    "-- Reynolds TPO synthetic data — 2026-Q2",
    "-- Generated by export-reynolds-sql.ts",
    "",
  ];

  for (const r of retailers) {
    lines.push(
      `INSERT OR REPLACE INTO Retailer (id, name, channel, circanaCoverage, priority, createdAt) VALUES (${escape(r.id)}, ${escape(r.name)}, ${escape(r.channel)}, ${r.circanaCoverage ? 1 : 0}, ${escape(r.priority)}, ${escape(r.createdAt)});`
    );
  }
  lines.push("");

  for (const s of skus) {
    lines.push(
      `INSERT OR REPLACE INTO SKU (id, skuCode, category, brand, unitCost, basePrice, createdAt) VALUES (${escape(s.id)}, ${escape(s.skuCode)}, ${escape(s.category)}, ${escape(s.brand)}, ${s.unitCost}, ${s.basePrice}, ${escape(s.createdAt)});`
    );
  }
  lines.push("");

  for (const e of events) {
    lines.push(
      `INSERT INTO PromoEvent (id, retailerId, skuId, periodStart, periodEnd, discountDepth, durationWeeks, baselineUnits, promoUnits, inventoryFlag, promoType, displaySupport, featureAd, createdAt) VALUES (${escape(e.id)}, ${escape(e.retailerId)}, ${escape(e.skuId)}, ${escape(e.periodStart)}, ${escape(e.periodEnd)}, ${e.discountDepth}, ${e.durationWeeks}, ${e.baselineUnits}, ${e.promoUnits}, ${escape(e.inventoryFlag)}, ${escape(e.promoType)}, ${e.displaySupport ? 1 : 0}, ${e.featureAd ? 1 : 0}, ${escape(e.createdAt)});`
    );
  }

  console.log(lines.join("\n"));
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
